name: cybersource_ios
description: iOS implementation of the cybersource plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    implements: cybersource
    platforms:
      ios:
        pluginClass: CybersourcePlugin
        dartPluginClass: CybersourceIOS

dependencies:
  flutter:
    sdk: flutter
  cybersource_platform_interface:
    path: ../cybersource_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
